name = "DiskArrayTools"
uuid = "fcd2136c-9f69-4db6-97e5-f31981721d63"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de>"]
version = "0.1.9"

[deps]
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
DiskArrays = "0.3.7,0.4"
Interpolations = "0.12, 0.13, 0.14, 0.15"
IterTools = "1"
OffsetArrays = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
